// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4rwr6L5uNkGoDQopmWA09V7X5-wvEK0',
    appId: '1:806656088598:web:6a379b80a173f17eb37337',
    messagingSenderId: '806656088598',
    projectId: 'coffee-shop-60ced',
    authDomain: 'coffee-shop-60ced.firebaseapp.com',
    storageBucket: 'coffee-shop-60ced.firebasestorage.app',
    measurementId: 'G-GCSJH6D29R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrS2-Q-1BdO03bnxcAV-ZTJ1tLmuuKZDU',
    appId: '1:806656088598:android:af47e99afaf2abb4b37337',
    messagingSenderId: '806656088598',
    projectId: 'coffee-shop-60ced',
    storageBucket: 'coffee-shop-60ced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA28bHBFIsFLirETZw06W3Gmz97MwzEmfU',
    appId: '1:806656088598:ios:645a1db61ff7ead1b37337',
    messagingSenderId: '806656088598',
    projectId: 'coffee-shop-60ced',
    storageBucket: 'coffee-shop-60ced.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA28bHBFIsFLirETZw06W3Gmz97MwzEmfU',
    appId: '1:806656088598:ios:645a1db61ff7ead1b37337',
    messagingSenderId: '806656088598',
    projectId: 'coffee-shop-60ced',
    storageBucket: 'coffee-shop-60ced.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF4rwr6L5uNkGoDQopmWA09V7X5-wvEK0',
    appId: '1:806656088598:web:afdd681aa217d2ffb37337',
    messagingSenderId: '806656088598',
    projectId: 'coffee-shop-60ced',
    authDomain: 'coffee-shop-60ced.firebaseapp.com',
    storageBucket: 'coffee-shop-60ced.firebasestorage.app',
    measurementId: 'G-VCRZGV7YSX',
  );
}
